name: "Ahmed Khalid"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: " login to Docker hub"
         run: docker login --username ahmedkhalid25 --password dckr_pat_BhooO4tFp93d9gGXFWmwOFGvYFk

      - name: " building docker "
         run: docker build -t ${{ secrets.DOCKER_USERNAME}}/task3 .
      - name: " pushing to docker hub "
         run: docker push ${{ secrets.DOCKER_USERNAME}}/task3


